config/routes.rb
Rails.application.routes.draw do
    get 'users/index'
    root 'home#index'
    devise_for :users, controllers: { sessions: "user/sessions"}
    resources :users, only: [:index, :show]
    resources :exercise_routines do
        resources :exercise_routine_exercises, only: [:new, :create]
    end
    resources :exercises, except: [:destroy] do
        resources :exercise_routine_exercises, only: [:new, :create]
    end
    resources :exercise_routine_exercises
    resources :friendships, only: [:new, :destroy]
    get 'home/index'
    get 'about', to: 'home#about'

    get '*path' => redirect('/')
end

app/models/exercise_routine.rb
class ExerciseRoutine < ApplicationRecord
    has_many :exercise_routine_exercises, -> { order(exercise_number: :asc)}
    has_many :exercises, through: :exercise_routine_exercises
    belongs_to :user

    enum visibility: {just_me: 0, friends: 1, everyone: 2}

    scope :public_exercise_routines, ->() {where(visibility: 2)}
    scope :friend_exercise_routines, ->(user) {where(user_id: user.id, visibility: 1)}


    def remove_exercise_from_routine(exercise_number)
        aray = exercise_routine_exercises.slice(exercise_number, exercise_routine_exercises.size - exercise_number)
        aray.each do |ere|
            ere.exercise_number -= 1
            ere.save
        end
    end
end

app/controllers/exercise_routines_controller.rb
class ExerciseRoutinesController < ApplicationController
    before_action :auth_user
    before_action :check_user_visibility, only: [:show]
    before_action :verify_user, only: [:edit, :update, :destroy]

    # GET /exercise_routines or /exercise_routines.json
    def index
        @exercise_routines = current_user.get_visible_exercise_routines
    end

    # GET /exercise_routines/1 or /exercise_routines/1.json
    def show
    end

    # GET /exercise_routines/new
    def new
        @exercise_routine = ExerciseRoutine.new
    end

    # GET /exercise_routines/1/edit
    def edit
    end

    # POST /exercise_routines or /exercise_routines.json
    def create
        @exercise_routine = ExerciseRoutine.new(exercise_routine_params)
        @exercise_routine.user = current_user

        respond_to do |format|
        if @exercise_routine.save
            format.html { redirect_to exercise_routine_url(@exercise_routine), notice: "Exercise routine was successfully created." }
            format.json { render :show, status: :created, location: @exercise_routine }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @exercise_routine.errors, status: :unprocessable_entity }
        end
        end
    end

    # PATCH/PUT /exercise_routines/1 or /exercise_routines/1.json
    def update
        respond_to do |format|
        if @exercise_routine.update(exercise_routine_params)
            format.html { redirect_to exercise_routine_url(@exercise_routine), notice: "Exercise routine was successfully updated." }
            format.json { render :show, status: :ok, location: @exercise_routine }
        else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @exercise_routine.errors, status: :unprocessable_entity }
        end
        end
    end

    # DELETE /exercise_routines/1 or /exercise_routines/1.json
    def destroy
        @exercise_routine.destroy

        respond_to do |format|
        format.html { redirect_to exercise_routines_url, notice: "Exercise routine was successfully destroyed." }
        format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_routine
        @exercise_routine = ExerciseRoutine.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def exercise_routine_params
        params.require(:exercise_routine).permit(:name, :description, :visibility)
    end

    def auth_user
        redirect_to new_user_session_path if !user_signed_in?
    end

    def verify_user
        set_exercise_routine
        redirect_to root_path if @exercise_routine.user != current_user
    end

    def check_user_visibility
        set_exercise_routine
        redirect_back_or_to root_path if !current_user.get_visible_exercise_routines.include?(@exercise_routine)
    end
end

app/helpers/exercise_routines_helper.rb
module ExerciseRoutinesHelper
end

app/views/exercise_routines/_form.html.erb
<%= form_with(model: exercise_routine) do |form| %>
  <% if exercise_routine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise_routine.errors.count, "error") %> prohibited this exercise_routine from being saved:</h2>

      <ul>
        <% exercise_routine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
    </div>
    <br/>
    <div class="field form-group">
        <%= form.label :visibility %>
        <%= form.select :visibility, options_for_select(ExerciseRoutine.visibilities.map {|key, value| [key.titleize, ExerciseRoutine.visibilities.key(value)]}, @exercise_routine.visibility), class: "form-control" %>
    </div>
    <br/>
    <div>
        <%= form.submit class:"btn btn-success" %>
    </div>
<% end %>

app/views/exercise_routines/edit.html.erb
<%= render "layouts/general_modal", title: "New Exercise Routine" do %>
    <%= render "form", exercise_routine: @exercise_routine %>
<% end %>

app/views/exercise_routines/index.html.erb
<h1>Exercise Routines</h1>

<table class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Exercises</th>
            <th>Shared By</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @exercise_routines.each do |er| %>
            <tr id="<%= dom_id er %>">
                <td><%= link_to er.name, er %></td>
                <td><%= er.description %></td>
                <td><%= er.exercises.size %></td>
                <td><%= er.user.full_name %></td>
                <td><%= button_to "View routine", exercise_routine_path(er), method: :get, class:"btn btn-sm btn-info" %></td>
                <% if er.user == current_user %>
                    <td><%= button_to "Edit routine", edit_exercise_routine_path(er), method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-sm btn-warning" %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<%= button_to "New exercise routine ", new_exercise_routine_path, method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-primary" %>

app/views/exercise_routines/new.html.erb
<%= render "layouts/general_modal", title: "New Exercise Routine" do %>
    <%= render "form", exercise_routine: @exercise_routine %>
<% end %>

app/views/exercise_routines/show.html.erb
<div id="<%= dom_id @exercise_routine %>" class="card border-secondary">
    <h4 class="card-header"> <%= @exercise_routine.name %> </h4>
    <div class="card-body">
        <p>
            <strong>Description:</strong>
            <%= @exercise_routine.description %>
        </p>

        <% if @exercise_routine.user == current_user %>
            <p>
                <strong>Visibility:</strong>
                <%= @exercise_routine.visibility.titleize %>
            </p>
        <% end %>

        <% if @exercise_routine.user == current_user %>
            <p>You created this exercise routine </p>
        <% else %>
            <p>
                <strong>Shared by:</strong>
                <%= @exercise_routine.user.full_name %>
            </p>
        <% end %>

        </div>
        <div class="btn-toolbar">
            <div class="btn-group me-3">
            </div>
            <div class="btn-group">
                <% if @exercise_routine.user == current_user %>
                    <%= button_to "Edit exercise routine", edit_exercise_routine_path(@exercise_routine), method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-primary" %>
                <% end %>
                <%= button_to "Back to exercise routines", exercise_routines_path, method: :get, class:"btn btn-secondary" %>
            </div>
        </div>
        <br/>
    </div>
    <br/>
    <div id="<%= dom_id @exercise_routine %> exercises" class="card border-secondary">
        <h4 class="card-header"> <%= @exercise_routine.name %> exercises</h4>
        <div class="card-body">
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Type</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @exercise_routine.exercise_routine_exercises.each do |ere| %>
                        <tr id="<%= dom_id ere.exercise %>">
                            <td><%= ere.exercise_number %></td>
                            <td><%= link_to ere.exercise.name, ere.exercise %></td>
                            <td><%= ere.exercise.description %></td>
                            <td><%= ere.exercise.exercise_type.titleize %></td>
                            <% if @exercise_routine.user == current_user %>
                                <td><%= button_to "Remove from Routine", exercise_routine_exercise_path(ere), method: :delete, class:"btn btn-sm btn-danger" %></td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
            </table>

            </div>
            <div class="btn-toolbar">
                <div class="btn-group me-3">
                </div>
                <% if @exercise_routine.user == current_user %>
                    <%= button_to "Add exercise to routine", new_exercise_routine_exercise_routine_exercise_path(@exercise_routine), method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-primary" %>
                <% end %>
            </div>
            <br/>
        </div>
        <br/>
    </div>
</div>