config/routes.rb
Rails.application.routes.draw do
    get 'users/index'
    root 'home#index'
    devise_for :users, controllers: { sessions: "user/sessions"}
    resources :users, only: [:index, :show]
    resources :exercise_routines do
        resources :exercise_routine_exercises, only: [:new, :create]
    end
    resources :exercises, except: [:destroy] do
        resources :exercise_routine_exercises, only: [:new, :create]
    end
    resources :exercise_routine_exercises
    resources :friendships, only: [:new, :destroy]
    get 'home/index'
    get 'about', to: 'home#about'

    get '*path' => redirect('/')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to new_user_session_path if !user_signed_in?
    end

    def about
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Exercise Companion", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to "About", about_path, class:"nav-link" %>
                </li>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Find Friends", users_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "View Exercise Routines", exercise_routines_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "View Exercises", exercises_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class:"nav-link" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                    <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
                    </li>
                <% end %>
                </ul>
        </div>
    </div>
</nav>

app/views/home/about.html.erb
About page

app/views/home/index.html.erb
<h1>Home Page</h1>