config/routes.rb
Rails.application.routes.draw do
    get 'users/index'
    root 'home#index'
    devise_for :users, controllers: { sessions: "user/sessions"}
    resources :users, only: [:index, :show]
    resources :exercise_routines do
        resources :exercise_routine_exercises, only: [:new, :create]
    end
    resources :exercises, except: [:destroy] do
        resources :exercise_routine_exercises, only: [:new, :create]
    end
    resources :exercise_routine_exercises
    resources :friendships, only: [:new, :destroy]
    get 'home/index'
    get 'about', to: 'home#about'

    get '*path' => redirect('/')
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    before_action :auth_user
    before_action :check_user_visibility, only: [:show]
    before_action :verify_user, only: [:edit, :update]

    # GET /exercises or /exercises.json
    def index
        @exercises = current_user.get_visible_exercises
    end

    # GET /exercises/1 or /exercises/1.json
    def show
    end

    # GET /exercises/new
    def new
        @exercise = Exercise.new
    end

    # GET /exercises/1/edit
    def edit
    end

    # POST /exercises or /exercises.json
    def create
        @exercise = Exercise.new(exercise_params)
        @exercise.user = current_user

        respond_to do |format|
        if @exercise.save
            format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully created." }
            format.json { render :show, status: :created, location: @exercise }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @exercise.errors, status: :unprocessable_entity }
            format.turbo_stream { render :form_update, status: :unprocessable_entity }
        end
        end
    end

    # PATCH/PUT /exercises/1 or /exercises/1.json
    def update
        respond_to do |format|
        if @exercise.update(exercise_params)
            format.html { redirect_back_or_to @exercise, notice: "Exercise was successfully updated." }
            format.json { render :show, status: :ok, location: @exercise }
        else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @exercise.errors, status: :unprocessable_entity }
            format.turbo_stream { render :form_update, status: :unprocessable_entity }
        end
        end
    end

    # DELETE /exercises/1 or /exercises/1.json
    def destroy
        @exercise.destroy

        respond_to do |format|
        format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
        format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
        @exercise = Exercise.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
        params.require(:exercise).permit(:name, :description, :visibility, :exercise_type)
    end

    def auth_user
        redirect_to new_user_session_path if !user_signed_in?
    end

    def verify_user
        set_exercise
        redirect_to root_path if @exercise.user != current_user
    end

    def check_user_visibility
        set_exercise
        redirect_to root_path if !current_user.get_visible_exercises.include?(@exercise)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
    <% if exercise.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

        <ul>
            <% exercise.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field form-group">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
    </div>
    <br/>
    <div class="field form-group">
        <%= form.label :visibility %>
        <%= form.select :visibility, options_for_select(Exercise.visibilities.map {|key, value| [key.titleize, Exercise.visibilities.key(value)]}, @exercise.visibility), class: "form-control" %>
    </div>
    <br/>
    <div class="field form-group">
        <%= form.label :exercise_type %>
        <%= form.select :exercise_type, options_for_select(Exercise.exercise_types.map {|key, value| [key.titleize, Exercise.exercise_types.key(value)]}, @exercise.exercise_type), class: "form-control" %>
    </div>
    <br/>
    <div>
        <%= form.submit class:"btn btn-success" %>
    </div>
<% end %>

app/views/exercises/edit.html.erb
<%= render "layouts/general_modal", title: "Edit Exercise" do %>
    <%= render "form", exercise: @exercise %>
<% end %>

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<table class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Type</th>
            <th>Shared By</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @exercises.each do |exercise| %>
            <tr id="<%= dom_id exercise %>">
                <td><%= link_to exercise.name, exercise %></td>
                <td><%= exercise.description %></td>
                <td><%= exercise.exercise_type.titleize %></td>
                <td><%= exercise.user.full_name %></td>
                <td><%= button_to "Add to Routine", new_exercise_exercise_routine_exercise_path(exercise), method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-sm btn-info" %></td>
                <% if exercise.user == current_user %>
                    <td><%= button_to "Edit exercise", edit_exercise_path(exercise), method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-sm btn-warning" %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<%= button_to "New exercise", new_exercise_path, method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-primary" %>

app/views/exercises/new.html.erb
<%= render "layouts/general_modal", title: "New Exercise" do %>
    <%= render "form", exercise: @exercise %>
<% end %>

app/views/exercises/show.html.erb
<div id="<%= dom_id @exercise %>" class="card border-secondary">
    <h4 class="card-header"> <%= @exercise.name %> </h4>
    <div class="card-body">
        <p>
            <strong>Description:</strong>
            <%= @exercise.description %>
        </p>

        <% if @exercise.user == current_user %>
            <p>
                <strong>Visibility:</strong>
                <%= @exercise.visibility.titleize %>
            </p>
        <% end %>

        <p>
            <strong>Type:</strong>
            <%= @exercise.exercise_type.titleize %>
        </p>

        <% if @exercise.user == current_user %>
            <p>You created this exercise </p>
        <% else %>
            <p>
                <strong>Shared by:</strong>
                <%= @exercise.user.full_name %>
            </p>
        <% end %>

        </div>
        <div class="btn-toolbar">
            <div class="btn-group me-3">
            </div>
            <div class="btn-group">
                <% if @exercise.user == current_user %>
                    <%= button_to "Edit exercise", edit_exercise_path(@exercise), method: :get, data: { turbo_frame: "general_modal"}, class:"btn btn-primary" %>
                <% end %>
                <%= button_to "Back to exercises", exercises_path, method: :get, class:"btn btn-secondary" %>
            </div>
        </div>
        <br/>
    </div>
</div>